using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;

namespace AK_Textile
{
    public partial class SalesCustomer : Form
    {
        private MainForm mainForm;

        //database connection
        SqlConnection con = new SqlConnection(@"Data Source=DESKTOP-SDPNF2L\MSSQLSERVER01;
                                                Initial Catalog=Textlies;
                                                Integrated Security=True");

        Form formBackground = null; // Declare outside to access in 'finally'
        public SalesCustomer(MainForm mainForm)
        {
            InitializeComponent();
            this.mainForm = mainForm;
        }

        private void SalesCustomer_Load(object sender, EventArgs e)
        {

        }

        private void pictureBox3_Click(object sender, EventArgs e)
        {
            mainForm.LoadForm(new SalesDashboard(mainForm));
        }

        private void pictureBox2_Click(object sender, EventArgs e)
        {
            mainForm.LoadForm(new LoginForm(mainForm));
        }

        private void button1_Click(object sender, EventArgs e)
        {
            mainForm.LoadForm(new SalesOrder(mainForm));
        }

        private void button2_Click(object sender, EventArgs e)
        {
            mainForm.LoadForm(new SalesSalesReturn(mainForm));
        }

        private void button3_Click(object sender, EventArgs e)
        {
            mainForm.LoadForm(new SalesPayment(mainForm));
        }

        private void button4_Click(object sender, EventArgs e)
        {
            mainForm.LoadForm(new SalesInvoice(mainForm));
        }

        private void button9_Click(object sender, EventArgs e)
        {
            mainForm.LoadForm(new SalesSchedule(mainForm));
        }

        private void button12_Click(object sender, EventArgs e)
        {
            mainForm.LoadForm(new SalesBill(mainForm));
        }

        private void button13_Click(object sender, EventArgs e)
        {
            mainForm.LoadForm(new SalesReport(mainForm));
        }

        private void linkLabel1_LinkClicked(object sender, LinkLabelLinkClickedEventArgs e)
        {
            mainForm.LoadForm(new LoginForm(mainForm));
        }

        private void button5_Click(object sender, EventArgs e)
        {
            this.textBox1.Clear();
        }

        private void button11_Click(object sender, EventArgs e)
        {
            // We assume separate input controls for new data (e.g., txtNewName, txtNewPhone).
            string newName = txtNewName.Text.Trim();
            string newPhone = txtNewPhone.Text.Trim();
            string newAddress = txtNewAddress.Text.Trim();

            if (string.IsNullOrEmpty(newName) || string.IsNullOrEmpty(newPhone))
            {
                MessageBox.Show("Please enter the required customer details (Name and Phone) before adding.", "Input Required", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            try
            {
                // Define the SQL query for insertion
                // Note: CustomerID is typically auto-generated by the database.
                string query = "INSERT INTO Customer (CustomerName, Phone, Address) VALUES (@Name, @Phone, @Address)";

                using (SqlConnection con = new SqlConnection(/* Your Connection String Here */))
                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    cmd.Parameters.AddWithValue("@Name", newName);
                    cmd.Parameters.AddWithValue("@Phone", newPhone);
                    cmd.Parameters.AddWithValue("@Address", newAddress);

                    con.Open();
                    int rowsAffected = cmd.ExecuteNonQuery();

                    if (rowsAffected > 0)
                    {
                        MessageBox.Show("New customer added successfully.", "Add Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
                        btnClear_Click(null, null); // Clear the form
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Database Error during addition: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void button6_Click(object sender, EventArgs e)
        {
            string searchInput = textBox1.Text.Trim();

            if (string.IsNullOrEmpty(searchInput))
            {
                MessageBox.Show("Please enter a Customer ID or Name to search.", "Input Required", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            try
            {
                // Define the SQL query to search by CustomerID or CustomerName
                string query = "SELECT * FROM Customer WHERE CustomerID = @Input OR CustomerName LIKE @NameInput";

                using (SqlConnection con = new SqlConnection(/* Your Connection String Here */))
                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    // Use parameters to prevent SQL Injection
                    cmd.Parameters.AddWithValue("@Input", searchInput);
                    cmd.Parameters.AddWithValue("@NameInput", "%" + searchInput + "%"); // Wildcard search for Name

                    con.Open();

                    using (SqlDataReader reader = cmd.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            // Customer Found: Display details
                            textBox1.Clear(); // Clear previous details

                            // Example of how to format and display the customer data
                            string details = $"Customer ID: {reader["CustomerID"]}\n" +
                                             $"Name: {reader["CustomerName"]}\n" +
                                             $"Phone: {reader["Phone"]}\n" +
                                             $"Address: {reader["Address"]}";

                            textBox1.Text = details;
                            MessageBox.Show("Customer record found.", "Search Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
                        }
                        else
                        {
                            // Customer Not Found
                            textBox1.Clear();
                            MessageBox.Show("No customer found matching the input.", "Not Found", MessageBoxButtons.OK, MessageBoxIcon.Information);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Database Error during search: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void button10_Click(object sender, EventArgs e)
        {
            // Check if a customer has been searched and its ID is stored
            if (string.IsNullOrEmpty(_currentCustomerID))
            {
                MessageBox.Show("Please search for a customer first before updating their record.", "Search Required", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            // --- IMPORTANT ASSUMPTION ---
            // We assume the details in input controls (e.g., txtNewName, txtNewPhone)
            // now contain the MODIFIED data.
            string modifiedName = txtNewName.Text.Trim();
            string modifiedPhone = txtNewPhone.Text.Trim();
            string modifiedAddress = txtNewAddress.Text.Trim();

            if (string.IsNullOrEmpty(modifiedName) || string.IsNullOrEmpty(modifiedPhone))
            {
                MessageBox.Show("Please ensure Name and Phone fields have data.", "Input Required", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            try
            {
                // SQL query to update the customer record based on the stored ID
                string query = "UPDATE Customer SET CustomerName = @Name, Phone = @Phone, Address = @Address WHERE CustomerID = @ID";

                using (SqlConnection con = new SqlConnection(/* Your Connection String Here */))
                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    // Set parameters for the updated data
                    cmd.Parameters.AddWithValue("@Name", modifiedName);
                    cmd.Parameters.AddWithValue("@Phone", modifiedPhone);
                    cmd.Parameters.AddWithValue("@Address", modifiedAddress);
                    cmd.Parameters.AddWithValue("@ID", _currentCustomerID);

                    con.Open();
                    int rowsAffected = cmd.ExecuteNonQuery();

                    if (rowsAffected > 0)
                    {
                        MessageBox.Show("Customer details updated successfully.", "Update Success", MessageBoxButtons.OK, MessageBoxIcon.Information);

                        // Clear the temporary ID and refresh the details display
                        _currentCustomerID = string.Empty;
                        btnClear_Click(null, null);
                    }
                    else
                    {
                        MessageBox.Show("No record was updated. Check the Customer ID.", "Update Failed", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Database Error during update: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

    }
}
